# Estructuras en Python - Conceptos

**Autor:** Jazna Meza Hidalgo

**Correo Electrónico:** ymeza@ubiobio.cl

**Fecha de Creación:** Agosto de 2026  
**Versión:** 1.0  

---

## Descripción

Este notebook ofrece la explicación del uso de las estructuras de Python para un análisis preliminar de los datos.

---

## Requisitos de Software

Este notebook fue desarrollado con Python 3.12. A continuación se listan las bibliotecas necesarias:

- pandas (>=1.1.0)
- matplotlib (3.7.1)
- numpy (2.0.2)

Para verificar la versión instalada ejecutar usando el siguiente comando, usando la librería de la cual quieres saber la versión:

```python
import pandas as pd
print(pd.__version__)
````

In [ ]:
import numpy as np
import pandas as pd

# Lista nativa

In [ ]:
notas = [55, 68, 72, 49, 80]

Aquí hay una lista nativa de Python.

---
**¿Qué ocurre si quiero sumar 5 puntos a todas las notas?**

---
Con una lista, normalmente se puede hacer:

In [ ]:
notas_nuevas = []

for nota in notas:
  notas_nuevas.append(nota + 5)

print(notas_nuevas)

[60, 73, 77, 54, 85]

**Concepto**

```text
Las listas de Python son estructuras generales.
No están diseñadas específicamente para realizar operaciones matemáticas masivas sobre datos numéricos.
```

Esta línea de código
```python
notas + 5
```

va a generar el error:

```
TypeError: can only concatenate list (not "int") to list
```

# Pasar de lista a NumPy

In [ ]:
notas = np.array([55, 68, 72, 49, 80])

In [ ]:
notas_nuevas = notas + 5

print(notas_nuevas)

[60 73 77 54 85]

Lo anterior es lo que se conoce como `Vectorización`, ya no es necesario hacer:

```python
for nota in notas:
  ...
```

**Importante**

**Vectorizar** no significa que internamente no exista ningún ciclo.

Significa que el ciclo de procesamiento está implementado en código optimizado de NumPy, generalmente en C, en lugar de ejecutarse elemento por elemento mediante el intérprete de Python.

# ¿Por qué `numpy` es más eficiente?

## Lista Python



Una lista almacena referencias a objetos Python:

```
Lista
┌────┬────┬────┬────┐
│ →  │ →  │ →  │ →  │
└─┬──┴─┬──┴─┬──┴─┬──┘
  ↓    ↓    ↓    ↓
 int  int  int  int

Incluso, los elementos pueden ser de distinto tipo:

```python
datos = [10, 3.14, "Hola", True]
```

Una lista es, por tanto, **flexible**, pero esa flexibilidad tiene un costo.

## `ndarray`

Un ndarray está pensado para trabajar con datos homogéneos:

```python
datos = np.array([10, 20, 30, 40])
```

Conceptualmente:
```text
┌────┬────┬────┬────┐
│ 10 │ 20 │ 30 │ 40 │
└────┴────┴────┴────┘
      memoria contigua
```

Todos los elementos tienen un tipo común:

```python
datos.dtype
```

retornará `int64`

In [ ]:
datos = np.array([10, 20, 30, 40])
datos.dtype

dtype('int64')

## Inspeccionar un `ndarray`

In [ ]:
X = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

In [ ]:
print(X.shape)
print(X.ndim)
print(X.dtype)

(2, 3)
2
int64

## Uso de `pandas`

In [ ]:
data = pd.DataFrame({
    "edad": [20, 25],
    "ingreso": [500000, 750000],
    "ciudad": ["Concepción", "Puerto Varas"]
})

In [ ]:
data.dtypes

edad        int64
ingreso     int64
ciudad     object
dtype: object

**NumPy**

Orientado principalmente a:
```text
datos numéricos homogéneos + operaciones matemáticas eficientes
```
**Pandas**

Orientado principalmente a:
```text
datos tabulares + etiquetas + columnas heterogéneas
```

# Series vs DataFrame

In [ ]:
edades = pd.Series([20, 25, 30], name="edad")

In [ ]:
data = pd.DataFrame({
    "edad": [20, 25, 30],
    "ingreso": [500000, 750000, 600000]
})

```text
          DataFrame
             │
      ┌──────┴──────┐
      ↓             ↓
   Series         Series
    edad          ingreso
```

# El concepto crítico: `.loc` vs `.iloc`

In [ ]:
data = pd.DataFrame({
    "nombre": ["Anacleto", "Mefistofeles", "Pericles"],
    "edad": [20, 25, 30],
    "nota": [6.1, 5.5, 6.8]
})
data

         nombre  edad  nota
0      Anacleto    20   6.1
1  Mefistofeles    25   5.5
2      Pericles    30   6.8

## `.iloc`: posición

In [ ]:
data.iloc[0]

nombre    Anacleto
edad            20
nota           6.1
Name: 0, dtype: object

`iloc` significa, conceptualmente:
```text
integer location
```
Trabaja con posiciones enteras.

In [ ]:
data.iloc[0, 1]

np.int64(20)

## `.loc`: etiqueta

In [ ]:
data.loc[0]

nombre    Anacleto
edad            20
nota           6.1
Name: 0, dtype: object

En cambio:
```python
data.loc[0]
```
significa:
```
Dame la fila cuya etiqueta de índice es 0.
```

Al principio parecen exactamente iguales:

```python
data.iloc[0]
data.loc[0]
```

Sin embargo, **SON DISTINTOS**

In [ ]:
data.index = ["A", "B", "C"]

In [ ]:
data

         nombre  edad  nota
A      Anacleto    20   6.1
B  Mefistofeles    25   5.5
C      Pericles    30   6.8

In [ ]:
data.loc["A"]

nombre    Anacleto
edad            20
nota           6.1
Name: A, dtype: object

In [ ]:
data.iloc[0]

nombre    Anacleto
edad            20
nota           6.1
Name: A, dtype: object

Sin embargo

```python
data.loc[0]
```

Marcará error:
```text
KeyError: 0
``

In [ ]:
data = pd.DataFrame(
    {
        "nombre": ["Ana", "Juan", "Pedro"],
        "nota": [6.1, 5.5, 6.8]
    },
    index=[101, 205, 310]
)
data

    nombre  nota
101    Ana   6.1
205   Juan   5.5
310  Pedro   6.8

In [ ]:
data.loc[205]

nombre    Juan
nota       5.5
Name: 205, dtype: object

In [ ]:
data.iloc[1]

nombre    Juan
nota       5.5
Name: 205, dtype: object

```python
data.iloc[205]
```

marcará error porque intentará buscar el elemento ubicado en la posición 205

y

```python
data.loc[1]
```

también marcará error porque busca una etiqueta 1 que tampoco existe.

# Conexión con `Machine Learning`

```text
              DATOS
                │
                ▼
        ┌───────────────┐
        │    Pandas     │
        │               │
        │ DataFrame     │
        │ índices       │
        │ columnas      │
        │ tipos mixtos  │
        └───────┬───────┘
                │
                │ selección / limpieza
                ▼
        ┌───────────────┐
        │     NumPy     │
        │               │
        │ ndarray       │
        │ vectorización │
        │ operaciones   │
        │ numéricas     │
        └───────┬───────┘
                │
                ▼
        ┌───────────────┐
        │ Scikit-Learn  │
        │               │
        │ X, y          │
        │ modelos       │
        │ predicciones  │
        └───────────────┘
```

# Ejercicio

In [ ]:
data = pd.DataFrame({
    "cliente": ["A", "B", "C", "D"],
    "edad": [22, 35, 41, 29],
    "ingreso": [450000, 800000, 1200000, 650000],
    "compras": [3, 8, 12, 5]
})

data

  cliente  edad  ingreso  compras
0       A    22   450000        3
1       B    35   800000        8
2       C    41  1200000       12
3       D    29   650000        5

In [ ]:
# Obtiene dimensiones
data.shape

(4, 4)

In [ ]:
# Obtiene tipos de datos
data.dtypes

cliente    object
edad        int64
ingreso     int64
compras     int64
dtype: object

Un `DataFrame` puede contener columnas de diferentes tipos, mientras que un `ndarray` normalmente trabaja con un tipo homogéneo.

In [ ]:
ingresos = data["ingreso"]
ingresos

0     450000
1     800000
2    1200000
3     650000
Name: ingreso, dtype: int64

Al seleccionar una sola columna se obtiene una `Series de Pandas`.

```text
DataFrame
    │
    ├── cliente  → Series
    ├── edad     → Series
    ├── ingreso  → Series
    └── compras  → Series
```

In [ ]:
type(ingresos)

pandas.core.series.Series

In [ ]:
primeras_filas = data.iloc[:2]
primeras_filas

  cliente  edad  ingreso  compras
0       A    22   450000        3
1       B    35   800000        8

In [ ]:
data.iloc[:2]

  cliente  edad  ingreso  compras
0       A    22   450000        3
1       B    35   800000        8

In [ ]:
fila_c = data.loc[2]
fila_c

cliente          C
edad            41
ingreso    1200000
compras         12
Name: 2, dtype: object

In [ ]:
X = data[["edad", "ingreso", "compras"]].to_numpy()
X

array([[     22,  450000,       3],
       [     35,  800000,       8],
       [     41, 1200000,      12],
       [     29,  650000,       5]])

In [ ]:
print(type(X))
print(X.shape)
print(X.ndim)
print(X.dtype)

<class 'numpy.ndarray'>
(4, 3)
2
int64

```text
DataFrame
   │
   │ seleccionar columnas
   ▼
data[["edad", "ingreso", "compras"]]
   │
   │ .to_numpy()
   ▼
ndarray
```

El resultado es una matriz de:

```
4 filas × 3 columnas
```

In [ ]:
promedio = np.mean(data["compras"].to_numpy())
promedio

np.float64(7.0)

In [ ]:
# Vectorización
data["ingreso_nuevo"] = data["ingreso"] * 1.10
data

  cliente  edad  ingreso  compras  ingreso_nuevo
0       A    22   450000        3       495000.0
1       B    35   800000        8       880000.0
2       C    41  1200000       12      1320000.0
3       D    29   650000        5       715000.0

```text
LISTAS PYTHON
     │
     │ datos generales
     ▼
  flexibilidad
     │
     ▼
NUMPY
     │
     ├── ndarray
     ├── datos homogéneos
     ├── memoria eficiente
     ├── vectorización
     └── operaciones numéricas
     │
     ▼
PANDAS
     │
     ├── Series
     ├── DataFrames
     ├── índices
     ├── columnas
     ├── datos heterogéneos
     └── loc / iloc
     │
     ▼
MACHINE LEARNING
     │
     ├── X
     ├── y
     ├── transformación
     └── modelos
```